### ISSUE TITLE
SQL(Databases)-Module success

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#56]
For clarity purposes and a better overview of the cohort's ability to move to the next module, there will be a simplified module success assessment. The existing one is not that useful.
- There will be 5 items that have to be done for the module to be complete and therefore the cohort to move to the next one.
- 3 will be tech-related and 1-2 PD-related per module.
- Example of a Tech one: 70% of the cohort is at or beyond milestones.

**Comment by LaraHuzjan** [comment]
@kfklein15 Please review the Module success suggestions written below. Feel free to look at the previous comments for comparison. 

- Demonstrate the ability to identify suitable job opportunities by successfully tailoring your resume accordingly for a minimum of 5 job applications.
- You have completed at least one Competency-Based mock interview

**Comment by kfklein15** [comment]
I am not sure we should leave the no 5 on the job application. But if you think i is an important number to on it, then leave it. Maybe do 2 instead of 5?

Demonstrate the ability to identify suitable job opportunities by successfully tailoring your resume accordingly to a job application.
You have completed at least one Competency-Based mock interview.

**Comment by LaraHuzjan** [comment]
I've uploaded everything, waiting to see if it'll go live.
MO [PRs](https://github.com/CodeYourFuture/curriculum/pull/591)

**Comment by kfklein15** [comment]
Merged
