### ISSUE TITLE
SQL(Databases)-Learning Objectives

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#88]
Improve the quality of previous Learning Objectives using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Comment by alfonsocanuk** [comment]
Hi @LaraHuzjan , based on what Esma did, here is my attempt. I do have a couple of concerns though:

1) These are looking more like tasks rather than objectives in my opinion.
2) In the first class exercise of Sprint 1 I think it is not well explained the difference between Definition of Done and Acceptance Criteria. I recommend this is reviewed.
3) I feel I keep reviewing same modules over and over again :( 




**Learning Objectives:**

**Sprint 1**
Current:
Explain the Agile principle of the importance of working software
Write a typical Definition of Done

Revised:
(Prep) Provide an example of a Definition of Done and an example of an Acceptance Criteria for a User Story.
(Class) Create a checklist that defines what’s needed for an increment to be releasable at the end of a Sprint.

**Sprint 2**
Current:
List four things that help you understand whether a job posting is worth applying for
Practice analysing how well real Job Descriptions match your skills and experience

Revised:
(Prep) Utilize online job search engines to identify 3 job postings that match your skills, experience and career goals based on requirements, common keywords and company values.
(Class) Review job descriptions in groups and come up with good questions to ask employers or recruiters before applying for a job.

**Sprint 3**
Current:
In 3 sentences, explain what competency-based questions are
Learn to identify key elements of a job description.
Identify your most relevant qualifications using the job description keywords and specific phrases so these can be included and highlighted in your resume.

Revised:
(Prep) Write 5 competency-based questions that you could expect on an interview and answer them.
(Class) Identify key elements of a job description for a software engineer role, including required skills, qualifications, and responsibilities.
(Class) Recognize the importance of tailoring a resume to match the requirements and priorities outlined in a job description.
(Class) Apply the STAR method to effectively answer competency-based interview questions related to the software engineer role.

**Sprint 4**
Current:
In two sentences, explain why it is important to look for jobs collaboratively.
As a group find 2 suitable job opportunities

Revised:
(Prep) Identify the benefits of collective job hunting in leveraging community strengths and support networks.
(Class) Find 2 suitable jobs applying search filters and techniques finding for job opportunities on LinkedIn Job Search.
(Class) Explain the potential advantages and disadvantages of hiring junior developers from the perspective of an Engineering Manager.

**Comment by LaraHuzjan** [comment]
1. If we look at Bloom's taxonomy we are using what I believe are correct words. They need to reflect actions. And it's measurable actions that they can prove/show by understanding the material - it's not an extra task for them to do if that makes sense.
2. In prep we have this [video](https://www.scrum.org/resources/definition-done-vs-acceptance-criteria) that talks about the difference. 
3. Not sure what you mean by that :/ not all of them have to be changed if you feel like they are ok. I believe towards the end we did a much better job compared to the beginning. 

Thanks for this, hope it was easier to navigate! 
Some of the revised ones do sound more like tasks now as they are longer. I'll suggest which to keep and then we can put it in the final review.

**Learning Objectives:**

**Sprint 1**
Current:
Explain the Agile principle of the importance of working software
Write a typical Definition of Done

Revised:
_(Prep) Provide an example of a Definition of Done for a user story
(Prep) Provide an example of an Acceptance Criteria for a User Story
(Class) Create a checklist that defines what’s needed for an increment to be releasable at the end of a Sprint._

**Sprint 2**
Current:
_List four things that help you understand whether a job posting is worth applying for_
Practice analysing how well real Job Descriptions match your skills and experience

Revised:
(Prep) Utilize online job search engines to identify 3 job postings that match your skills, experience and career goals based on requirements, common keywords and company values.
_(Class) Review job descriptions in groups and come up with good questions to ask employers or recruiters before applying for a job._

**Sprint 3**
Current:
_In 3 sentences, explain what competency-based questions are_
Learn to identify key elements of a job description.
Identify your most relevant qualifications using the job description keywords and specific phrases so these can be included and highlighted in your resume.

Revised:
(Prep) Write 5 competency-based questions that you could expect on an interview and answer them.
_(Class) Identify key elements of a job description for a software engineer role, including required skills, qualifications, and responsibilities._
_(Class) Recognize the importance of tailoring a resume to match the requirements and priorities outlined in a job description.
(Class) Apply the STAR method to effectively answer competency-based interview questions related to the software engineer role._

**Sprint 4**
Current:
_In two sentences, explain why it is important to look for jobs collaboratively._
As a group find 2 suitable job opportunities

Revised:
(Prep) Identify the benefits of collective job hunting in leveraging community strengths and support networks.
_(Class) Find 2 suitable jobs applying search filters and techniques finding for job opportunities on LinkedIn Job Search.
(Class) Explain the potential advantages and disadvantages of hiring junior developers from the perspective of an Engineering Manager._

@kfklein15 these can be reviewed. The ones I thought were more suitable I wrote in Italic. But do let us know what you think.

**Comment by kfklein15** [comment]
They all look great. Ready to upload.

**Comment by LaraHuzjan** [comment]
Updated!
